### ISSUE TITLE
When English text is displayed character by character, there are glitches due to automatic line breaks.

### ISSUE THREAD

**Issue by Sumaaaaaaaa** [emptygamer/flower#1]
When I try using English text, displaying it character by character, there occurs an issue where words from a previous frame that were at the end of the first line automatically move to the next line due to automatic line breaking. 

I discovered that the character-by-character display is implemented through the `Text` component. Could this be a difficult problem to solve?

**Comment by emptygamer** [comment]
Hello, 
the line breaking logic is a part of the <code>Text</code> component and it's immutable,
so you can create your text renderer to handle the line breaking logic to prevent the glitches.
1. Create your own text renderer.
2. Update your text via the <code>textUpdated</code> event handler.

If you want to use the Unity <code>Text</code> component, here are some tips.
1. Go to <code>DefaultDialogPrefab/DialogPanel/DialogText</code> and set the horizontal overflow to "overflow".
2. Set up your own line breaking logic via the <code>textUpdated</code> event handler by adding the new-line character in some scenarios.

Hope these are helpful :)

**Comment by emptygamer** [comment]
Done at Flower v2.2 with Flower default text splitting logic ( •̀ ω •́ )✧
```
flowerSys.SetupDialog("DefaultDialogPrefab",true,true);
```
https://github.com/emptygamer/flower/releases/tag/v2.2.0
