### ISSUE TITLE
對話自動播放

### ISSUE THREAD

**Issue by cin-gf** [emptygamer/flower#2]
您好，不好意思，請問若要使用您所撰寫的這些方法，在對話場景中要新增一個按鈕，可切換讓對話變成自動播放的話，應該要怎麼做比較好呢?
自動播放若還得再根據角色配音時間播完才可下一句的話，需要怎麼做比較好呢?

**Comment by emptygamer** [comment]
- 自動播放可以在 UsageCase 內設定一個變數來控制自動播放，當變數為 true 在 Update 內不斷呼叫 flowerSys.Next(); 即可。
- 等待配音可能要修改 audio 或透過自定義指令用 WaitUntil 等待特定的音訊播放完畢，可以再稍等後續的版本，應該會添加上去~

**Comment by emptygamer** [comment]
自動播放跟等待audio在Flower v2.2新增囉 ( •̀ ω •́ )✧
https://github.com/emptygamer/flower/releases/tag/v2.2.0
