### ISSUE TITLE
圖像

### ISSUE THREAD

**Issue by cin-gf** [emptygamer/flower#3]
若[image,k,King,500,-40,100]要在對話框上層的話，請問應該怎麼設定比較好呢?

**Comment by emptygamer** [comment]
因為 image sprite 是在 World Space，對話框 UI 是在 Screen Space，
所以簡易的做法是可以把 Dialog Prefab 調到 World Space 試試，只是這樣來回切換就會比較麻煩（；´д｀）ゞ

或是可以再等等下個版本，會加入 ui-image 的功能，就可以自己調整渲染順序~

**Comment by cin-gf** [comment]
好得  非常謝謝您!

**Comment by emptygamer** [comment]
UI Stage在Flower v2.2新增囉 ( •̀ ω •́ )✧
https://github.com/emptygamer/flower/releases/tag/v2.2.0
